version: "3.8"

services:
  vue_app_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/src/app:rw
    ports:
      - "5173:5173"
    environment:
      - API_URL="https://jsonplaceholder.typicode.com/"
