/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardView: typeof import('./components/Cart/CardView.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Modal: typeof import('./components/commons/Modal.vue')['default']
    Navbar: typeof import('./components/commons/Navbar.vue')['default']
    PageState: typeof import('./components/commons/PageState.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
